services:
  frontend:
    container_name: tcg-ims4-frontend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
      - docker-compose.env
    ports:
      - "3069:3000"
    restart: unless-stopped
