services:
  frontend:
    container_name: tcg-ims4-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_CONVEX_URL: ${VITE_CONVEX_URL}
        VITE_CONVEX_SITE_URL: ${VITE_CONVEX_SITE_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped
